js/render.js
js/script.js
styles/style.less
templates/game.mustache

I confess to have been led astray by the wonders of Youtube tonight, so I've done little of profit. I did reduce the O(n3) to O(nlogn), which is nice, but ultimately not critical and not really moving forward much.
In any case, here it is!

Reduce complexity of search

---

.gitignore
README.md
index.html
js/game.js
js/game.test.js
js/render.js
package-lock.json
package.json
templates/game.mustache

For this I brought npm into the project, although it's only needed to
execute the tests.
It currently has a 100% coverage of the game.js file (previously known
as script.js). Although I didn't find any bugs in the actual code, it
made me do some changes to the code structure so now it should be
slightly better.
It would be great to add a GitHub action to ensure that the tests keep
on passing and maybe even to ensure that we don't go below 100%
anymore.
Sorry for the 11K extra lines of package-lock.json, but it's recommended
to keep it in version control.

Adds game tests

---

js/game.js
js/game.test.js

Just the game.js with their corresponding tests. We will need to add UI
to call them and figure out if the game status covers the rendering
needs.

Adds bets functions

---

js/game.js
js/render.js
styles/style.less
templates/game.mustache

I modified the template and styling for the new betting features. I also added a generic explanation textbox on top for a welcome message and detailing what each step is about (barely a stub for now).
I also did some styling to the best of my colour abilities (I've been thinking nonstop about Villol this days! XD). Today was drop shadow day. Let's see what you think.
I got a draft of the list of things we need to do next, which I'll share with you tomorrow.

Iterates on interface for new bet features

---

README.md
index.html
js/ai.js
js/game.js
js/game.test.js
js/render.js
styles/style.less

Also added the game/no-game checks and other related improvements.

Adds basic AI

---

js/ai.js
js/game.js
js/render.js
styles/style.less
templates/game.mustache

LESS file? more like MESS am i right? (repeated values, etc)
I will refactor it a bit after this is merged.

Adds alert and help as modal dialogs

---

js/game.js
js/game.test.js
js/render.js
styles/style.less
templates/game.mustache

It still doesn't change the first player to talk and the results view
requires a lot of work, but at least displays both sets of dice.

Adds results and round loop

---

styles/style.less

Not a lot of changes, but cleaner and clearer already.

Use variables and group stylings in the CSS

---

js/ai.js
js/game.js
js/game.test.js
templates/game.mustache

When it's time for the AI to act, you'll arrive at the subgame with
their action already taken.

Adds player/rival starting logic

---

js/game.js

Just like rerolling, but also on the first step.

Adds initial rolling animation

---

js/render.js

Due to a seemingly innocent change, the initial rolling animation broke.
But the real reason is that we're fetching the Mustache template in an
async function so the game state could change between calling the render
function and the actual rendering. I've changed it to ensure that only
the very first time the template is fetched, guaranteeing that
successive calls are done in the same thread.

Fixes initial roll animation

---

js/ai.js
js/game.js
js/game.test.js
package.json

Also implements a few behaviour changes in the AI to make it stronger in
edge cases.
Restores the old Fold/Pass behaviour because I'm not sure if there's an actual issue there.

Fixes rival ending the subgame when talking first

---

README.md
js/ai.js
js/game.js
js/game.test.js
js/render.js
js/text.js

Now, as in Mus, 1 point will be resolved in the results step.
To be honest, at this time, I just feel like slapping some ugly "ifs" and calling it done.

Changes rule for both passing

---

js/text.js

Taken from the README, with minor adjustments.

Adds help and credits

---

styles/style.less
templates/game.mustache

I've also made the border consistent, because I wasn't sure if it was
intended to sometimes be dashed and sometimes not and it looked like a
bug to me.

Fixes user being able to select/deselect dice outside of rolling

---

README.md
js/game.js
js/render.js
js/text.js
styles/style.less
templates/game.mustache

(This needs to be rebased prior to merging)
Some things look bad now but I will fix in a separate branch, such as the help menu including buttons.

Rework styles to be proportional and work better across screens

---

styles/style.less

I like it more this way. If you agree, we can merge. If not, we can discard this.

Removes rival opacity

---

README.md
js/game.js
js/game.test.js

Brings the coverage back to 100%.

Adds simple test to playAgain()

---

styles/style.less

Besides adjusting heights on small screens, I made the scoreboards blue instead of violet and switched the dashed borders for borders (I do think this way it's clearer it's a hint).

Add stylings for small screens

---

js/game.js
js/render.js

Select no dice at end of round/finish. Use "Bet" instead of "Raise" when the rival started and passed.

Small stuff
